version: "3.9"
services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: ./python_api
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/logsdb
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  cpp-ingestor:
    build: ./cpp_ingestor
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27017/logsdb
      - LOG_FILE_PATH=/data/logs/logs.txt
      - WORKER_COUNT=4
    volumes:
      - ./logs/logs.txt:/data/logs/logs.txt:ro
    depends_on:
      - mongo
volumes:
  mongo_data:
